config/routes.rb
Rails.application.routes.draw do
  root "home#show"

  get    "/auth/:provider/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users,   only: [:edit, :update, :show]
  resources :matches, only: [:show, :update]

  get "/dashboard", to: "dashboard#show"
end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :userlanguages, dependent: :destroy
  has_many :users, through: :userlanguages, dependent: :destroy
end

app/models/match.rb
class Match < ActiveRecord::Base
  enum status: [ :inactive, :pending, :rejected, :approved ]

  def self.approved_matches(user)
    where(potential_match_id: user.id, status: 3)
  end

  def self.pending_matches(user)
    where.not(user_id: user.id)
    where(potential_match_id: user.id, status: 1)
    .pluck(:user_id)
  end

  def self.pending_matches_first(user)
    pending_matches = pending_matches(user)
    user.potential_matches - pending_matches
    user.potential_matches = pending_matches + user.potential_matches
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :userlanguages, dependent: :destroy
  has_many :languages, through: :userlanguages, dependent: :destroy

  def self.find_or_create_from_auth(data)
    user = User.find_or_initialize_by(provider: data.provider, uid: data.uid)

    user.login      = data.extra.raw_info.login
    user.avatar_url = data.extra.raw_info.avatar_url
    user.token      = data.credentials.token
    user.save

    user
  end

  def self.populate_potential_matches(user)
    if user.potential_matches.empty?
      User.all.each do |u|
        unless u.id == user.id
          user.potential_matches << u.id
        end
      end
    end
    user.potential_matches.shuffle!
    user.save!
  end
end

app/models/userlanguage.rb
class Userlanguage < ActiveRecord::Base
  belongs_to :user
  belongs_to :language
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  private

  def require_login
    unless current_user
      redirect_to root_path
      flash[:notice] = "Login required"
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    Match.pending_matches_first(current_user)

    @random_user = User.find(current_user.potential_matches.first)

    approved_matches = Match.approved_matches(current_user)
    @approved_pairs  = approved_matches.map do |match|
      User.find(match.user_id)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login

  def show
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @random_user = User.find(params[:id])
  end

  def update
    potential_match_id = params[:id].to_i
    status             = params[:status]

    potential_match = Match.find_by(user_id: potential_match_id)
    if potential_match
      if potential_match.status == "pending" && status == "pending"
        potential_match.update_attributes(status: 3)
        Match.create(user_id: current_user.id,
                     potential_match_id: potential_match_id,
                     status: "approved")
        matched_user = User.find(potential_match_id)
        flash[:notice] = "Congrats #{current_user.login}, you and #{matched_user.login} are a good match!"
      end
    end
    Match.create(user_id: current_user.id,
                 potential_match_id: potential_match_id,
                 status: status)

    current_user.potential_matches.delete(potential_match_id)
    current_user.save!

    next_random_user = User.find(current_user.potential_matches.first)
    redirect_to match_path(next_random_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def create
    user = User.find_or_create_from_auth(request.env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      if user.languages.empty?
        redirect_to edit_user_path(user)
      else
        redirect_to dashboard_path
        flash[:success] = "Welcome #{user.login}"
      end
      user.save
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
    flash[:success] = "Successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_user

  def show
  end

  def edit
    @languages = Language.all
    User.populate_potential_matches(current_user)
  end

  def update
    current_user.languages.delete_all
    user_languages = params[:languages]
    user_languages.each do |lang|
      language = Language.find_by(name: lang)
      current_user.languages << language
    end
    current_user.update_attributes(description: params[:description])
    current_user.save

    redirect_to current_user
  end

  private

  def authorize_user
    redirect_to dashboard_path if current_user.id != params[:id].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<div class="container">
  <div class="row">

    <h3 class="col s12">Matches</h3>

    <% if @approved_pairs.empty? %>
      <p>No matches yet!</p>
    <% else %>
      <table class="striped">
        <thead>
          <tr>
            <th data-field="id">Name</th>
          </tr>
        </thead>
        <tbody>
          <% @approved_pairs.each do |pair| %>
            <tr>
              <td><%= pair.login %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div> <!-- row -->
  <div class="row">
    <%= button_to "Find Pairs", match_path(@random_user), method: :get, class: "btn" %>
  </div>
</div>

app/views/home/show.html.erb
<div class="container">
  <div class="center-align">
    <h1>Please <%= link_to "Login", "/auth/github" %> to continue</h1>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "Pairr", dashboard_path, class: "brand-logo" %>
    <%= link_to "#", data: { activates: "mobile-demo" }, class: "button-collapse" do %>
      <i class="mdi-navigation-menu"></i>
    <% end %>
    <div class="right-align">
      <ul class="right hide-on-med-and-down">
        <% if current_user %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", "/auth/github" %></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if current_user %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairr</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render "layouts/navbar" %>

    <% flash.each do |name, message| %>
      <div class="container">
        <div class="card-panel teal lighten-5">
          <%= content_tag :div, message, class: name %>
        </div>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/matches/show.html.erb
<div class="container">
  <div class="row">

    <div class="col s12 m5">
      <div class="card">
        <div class="card-image">
          <%= image_tag @random_user.avatar_url %>
          <span class="card-title"><%= @random_user.login %></span>
        </div>
        <div class="card-content">
          <%= @random_user.description %>
          <h5>Preferred Languages</h6>
          <% @random_user.languages.each do |lang| %>
            <%= lang.name %>,
          <% end %>
        </div>

        <div class="card-action center-align">
          <%= button_to "Approve", match_path(@random_user), params: { status: "pending" }, action: :update, method: :patch, class: "btn col s6" %>
          <%= button_to "Reject", match_path(@random_user),  params: { status: "rejected" },  action: :update, method: :patch, class: "btn col s6"%>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <h2>User Information</h2>
    <p>Hey there <%= link_to current_user.login, current_user %>. Can you tell us a bit about yourself?</p>

    <%= form_for current_user, url: user_path(current_user), html: { method: "patch" } do |f| %>
      <h4>Brief Description of yourself</h4>
      <div class="input-field col s12">
        <textarea id="user-description" class="materialize-textarea" name="description" length="500" required="required"></textarea><br />
        <label for="user-description">What are you looking for in a pair? What are your interests?</label>
      </div>
      <h4>Preferred Languages</h4>
      <% @languages.each do |lang| %>
        <input id="<%= lang.name %>" name="languages[]" type="checkbox" value="<%= lang.name %>" />
        <label for="<%= lang.name %>"><%= lang.name %></label><br />
      <% end %>
      <input type="submit" value="Update info" class="btn" disabled/>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col s12 m5">
      <div class="card">
        <div class="card-image">
          <%= image_tag current_user.avatar_url %>
          <span class="card-title"><%= current_user.login %></span>
        </div>

        <div class="card-content">
          <%= current_user.description %>
          <h5>Preferred Languages</h5>
          <% current_user.languages.each do |lang| %>
            <%= lang.name %>,
          <% end %>
        </div>

        <div class="card-action center-align">
          <%= link_to "Update info", edit_user_path(current_user) %>
          <%= link_to "Logout", logout_path, method: :delete %>
        </div>
      </div>
    </div>

  </div>
</div>